# Generated by Django 2.2.16 on 2020-11-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eol_course_email', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EolCourseEmailUserConfiguration',
        ),
    ]
