# Generated by Django 2.2.19 on 2021-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eol_course_email', '0002_delete_eolcourseemailuserconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesCourseEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_path', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='eolcourseemail',
            name='files',
            field=models.ManyToManyField(to='eol_course_email.FilesCourseEmail'),
        ),
    ]
