# Generated by Django 2.2.19 on 2021-05-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eol_course_email', '0003_auto_20210525_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='filescourseemail',
            name='content_type',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
